export default {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    LOGOUT: 'LOGOUT',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    FETCH_ALL_BOOKS: 'FETCH_BOOKS',
    FETCH_USER_BOOKS: 'FETCH_USER_BOOKS',
    ADD_BOOK: 'ADD_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    REQUEST_BOOK: 'REQUEST_BOOK',
    FETCH_INC_REQUESTS: 'FETCH_INC_REQUESTS',
    FETCH_OUT_REQUESTS: 'FETCH_OUT_REQUESTS',
    APPROVE_REQUEST: 'APPROVE_REQUEST',
    REJECT_REQUEST: 'REJECT_REQUEST'
}